### ISSUE TITLE
bug: Nopol is sometimes non-deterministic (patch found / not found for the same input + command line parameters)

### ISSUE THREAD

**Issue by DehengYang** [SpoonLabs/nopol#146]
![12-1 angelic value](https://user-images.githubusercontent.com/32570286/33510057-8456b7fa-d6bc-11e7-95b1-3ab512aa0ba2.png)

In the paper of Nopol published in 2017, it describes that "NOPOL arbitrarily  tunes  a  conditional  value ..." I am confused about that if the Nopol randomly generates the angelic values in the step of repair for each statement.

Another question is that, can Nopol generate different (which means inequivalent) plausible patches by repairing the same buggy statement? I mean, if the Nopol arbitrarily tunes a conditional value, can it generate different patches that can pass all tests because of its randomness?

Thank you!

**Comment by monperrus** [comment]
Hi,

There is no randomness in the angelic value mining.

Nopol can generate different patches for the same buggy statement with the Dynamoth synthesis engine.

**Comment by DehengYang** [comment]
Thank you so much for your reply!

But I still have some doubt on the Angelic fix localization technique, because when I ran the Nopol repeatedly on the same buggy program, for instance Time_12 from defects4j, with same parameters and same environment of CPU and memory, I found that some repair trails, maybe 5 out of 100, tried to repair the faulty statement but failed, due to which there is no plausible patch found.

I would like to show some output of the repair information:
Nomally, the trails that generate plausible patches output:
"the repaired suspicious statement: 
org.joda.time.LocalDateTime : 663
suspiciousValue:  0.1903323805723546
the repair time for this statement is: 1920ms"

In contrast, the failed trails which cannot get expected patches output:
the repaired suspicious statement: 
"org.joda.time.LocalDateTime : 663
suspiciousValue:  0.1903323805723546
the repair time for this statement is: 62794ms"
(these failed trails also repaired the faulty statement and even consumed much more time. However, they still cannot get the patch 

So my doubt is that, if there is no randomness in the angelic fix localization, the repeated repair trails are supposed to get the same patch results rather than some trails can not generate any patches to pass all test cases.

Quite sorry for my disturbing in this issue. And thank you again for your kindness and patience！

**Comment by monperrus** [comment]
Interesting.

Is Time_12 fully deterministic? Does it depend on the current date / time of the day?

**Comment by tdurieux** [comment]
all the time bugs are awful  to reproduce.
it depends on the environment, jvm, ... I cannot reproduce it on my machine, but it works on my servers.
I may introduce some randomness.

**Comment by monperrus** [comment]
> Is "Angelic Fix Localization" a random algorithm when generating the angelic values?

So the answer is no, angelic value mining is not random, it is deterministic.

Nopol is designed to be deterministic as long as the code under repair is deterministic. (However, this has never been strongly tested, and there may be spurious causes of non-determinism, eg the order of test execution)

**Comment by DehengYang** [comment]
I am sorry that I reply so late. This phenomenon does not only occur in Time_12, it also happens in the repair process of Math_85, the buggy program from defects4j. I am not sure but personally I think that Math_85 is fully deterministic.

The details are as follow:
I set the --maxTimeType as 30 seconds (it is originally 5 minutes but I think it is kind of long so I set this to 30 seconds), however, the it costs more than twice the 30 seconds to repair the faulty statement, and unexpectedly, it doesn't generate plausible patch when repair the faulty statement. 

the output information is as follow:

"the repaired suspicious statement:
org.apache.commons.math.analysis.solvers.UnivariateRealSolverUtils : 198
suspiciousValue: 0.058823529411764705
the repair time for this statement is: 64688ms"

another failed repair output is:

"the repaired suspicious statement:
org.apache.commons.math.analysis.solvers.UnivariateRealSolverUtils : 198
suspiciousValue: 0.058823529411764705
the repair time for this statement is: 19794ms" (The repair time is less than 30s in this case)

But these failed repair trails, where Nopol repair the faulty statement but do not generate the expected patch, just account for a very small percentage, for instance 2 out of 100 in Math_85.

So this strange phenomenon about the Nopol repair still puzzles me. Can these failed trails be interpreted as a small bug of Nopol?

Thank you for your answer and guidance!

**Comment by tdurieux** [comment]
In this probably due to this:
> I set the --maxTimeType as 30 seconds (it is originally 5 minutes but I think it is kind of long so I set this to 30 seconds), 

Personally I use 20min to be sure

**Comment by monperrus** [comment]
> But these failed repair trails, where Nopol repair the faulty statement but do not generate the
> expected patch, just account for a very small percentage, for instance 2 out of 100 in Math_85. So
> this strange phenomenon about the Nopol repair still puzzles me.
>
It puzzles me as well
>
> Can these failed trails be interpreted as a small bug of Nopol?
>
May be. Or because of some hidden non-determinism somewhere (in Gzoltar, in Nopol, in Z3, ...)

Please keep us informed when you'll find the explanation.

**Comment by monperrus** [comment]
Reopening this issue since @SophieHYe has hit it again

**Comment by monperrus** [comment]
Now that we have Nopol on Jenkins, the flaky test is hitting us: https://ci.inria.fr/sos/job/nopol/35/display/redirect

**Comment by monperrus** [comment]
Current analysis ongoing by  @SophieHYe

The assumption is that it's due to tests running at different speed from one execution to another, and sometimes triggerring a timeout (either a Junit timeout or a Nopol-Testrunner timeout). Depending on those varying failing tests, this impacts the number of collected constraints (aka `Specifications` in Nopol).
 
There is no straightforward solution, @SophieHYe is working on this and will make a tentative PR about this.

**Comment by SophieHYe** [comment]
Hi,

Sharing  more details of this case here:

Background informaton: we found out Nopol is non-determine to find out a patch from time to time with a the same command line in the same machine. After checking, we noted in patch found case Nopol collected more specifications than the patch not-found case. Then we looked into the reason, because the specifications are collected only when the test listener is notified with the successful test run in TestSuiteExecution.  In other word, if the tests are fail, there is no specifications collection. So the problem turns into why sometimes the tests fail but sometimes succeed in TestSuiteExecution.

One found out is that we put a timeout in our Junit test ( 3 seconds).So when using the Junit test runner in Nopol, if the test is not finished, then this test is considered as fail test and the listener will not be notified. When we remove this timeout setting from our test, we still have the same situation and even worse because some tests are failed because the Nopol timeout.

In addition, we noted that the specifications collected are non-determined and the tests fail due to many reason besides timeout. We are trying to improve it.

**Comment by SophieHYe** [comment]
For many cases, another possibility that Nopol results are non-deterministic. Comparing the patch found and patch not found data, we found that same input value but with different outputs. This is because Nopol discard the second one if there are two different outcomes for the same input value. However, the tests execution sequence is random, which means our specification collection randomly collect one result and discard the contradictory one. Thus our specifications collected are non-deterministic and Nopol result is non-deterministic.

**Comment by monperrus** [comment]
Thanks a lot for the very thorough analysis.

For both the Junit / Nopol per-test-timeout exception, as discussed together, I think that stopping the repair process is the best solution, it's fail-fast, and the action to be taken by the user is very clear (increasing the Junit timeout or the Nopol test timeout). Would you do a pull request to remove the corresponding catch blocks?

For the collection of constraints (ie specification), I'm in favor of redesigning it, and we keep the discussion in #153.

**Comment by monperrus** [comment]
It seems that we have the final answer:

If one test fails due to timeout -- Junit timeout (`@Test(timeout=1000)`) or Nopol timeout (see Nopol config param `timeoutTestExecution` -- then determinism cannot be guaranteed anymore.

However, the timeout must be kept to prevent infinite loops during angelic value mining.

If this happens, the corresponding timeout must be increased.
