### ISSUE TITLE
Nopol generates an overfitted patches with a test suite, but a correct patch with a subset of the test suite

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [SpoonLabs/nopol#210]
I observed that Nopol generates an overfitted patches for a buggy program with a test suite. However, when I used a subset of the test suite, Nopol generates a correct patch.

 What can be the reason for this behavior?

Thank you in advance for your help and time.

**Comment by monperrus** [comment]
This happens.

This is because too much tests make an SMT spec which can be only satisfied by hard-wiring corner cases in the patch, which is consequently overfitting.

See @zhongxingyu's paper [Alleviating Patch Overfitting with Automatic Test Generation: A Study of Feasibility and Effectiveness for the Nopol Repair System](https://hal.inria.fr/hal-01774223/file/alleviating_Overfitting.pdf) ([doi:10.1007/s10664-018-9619-4](https://doi.org/10.1007/s10664-018-9619-4))
