### ISSUE TITLE
Generate an overfitted patch for repairing a bug with a test suite, but fix it correctly with a subset of the test suite

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [SpoonLabs/nopol#215]
Hi,

There is a buggy program that Nopol generates an overfitted patches with a test suite. However, when I use a subset of the test suite, then Nopol can fix it correctly. 

How can it be possible?

Thank you for your time and consideration in advance.

**Comment by monperrus** [comment]
Hi @Amirfarhad-Nilizadeh 

This is entirely possible. This is because more tests means a more convoluted synthesis problem, encouraging overfitting patches.

On this topic, see [Alleviating Patch Overfitting with Automatic Test Generation: A Study of Feasibility and Effectiveness for the Nopol Repair System](https://hal.inria.fr/hal-01774223/file/alleviating_Overfitting.pdf) ([doi:10.1007/s10664-018-9619-4](https://doi.org/10.1007/s10664-018-9619-4))

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you for your response.
