### ISSUE TITLE
improve log 

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#34]
from Ariel

what are expected to be the inputs listed after the following line on NOPOL's output?

10:02:33.611 [main] DEBUG f.i.l.c.s.ConstraintBasedSynthesis - Specifications:
input: {.....}
input: {.....}
...

maybe the constraints imposed by passing tests which execute the statement being patched?

**Comment by agodio** [comment]
Looking at the new SpecificationTestCasesListener debug messages, now I understand the meaning of "input: {.....}".

each "input: {.....}" refers to the data collected in the phase of runtime trace collection. It is NOT the input value of the program being repaired, despite the former depends on the later.
For a fixed source location and a test, regardless it fails or not, which executes it, there is exactly one "input: {.....}".

Due to the data collected does not necessarily comprehends the whole state of the program (just for efficiency), It is likely to happen that two different tests produce the same "input: {.....}" for a fixed source location _loc_. If it happens and the expected outcome (to make both tests pass) of the condition at _loc_ differ, NOPOL reports

> Same input with different outcome, logical contradiction, discarding the second one..

I think it is important to remark that this "logical contradiction" has to do with (probably not the right expression) "NOPOLS's blindness" at collecting data due to its configuration / capabilities. Maybe a more exhaustive runtime trace collection would let NOPOL find a patch, to the detriment of efficiency.

Now a question.

I know NOPOL collects the values of all local variables, method parameters, and class fields that are typed with a basic primitive type, but what about public fields of locally defined objects?

```
class MyClass{
  public int value;
}

foo(){
  MyClass bar = new MyClass();
  bar.value = <any value from anywhere>
  //int nopolHack = bar.value;
  ...
}
```

the value of bar.value wouldn't be collected unless I uncomment the last assignment. How can I make NOPOL collect this data?

**Comment by monperrus** [comment]
@danglotb so the fix for this one is simply to rename "input:" in "collected data:".

**Comment by monperrus** [comment]
> How can I make NOPOL collect this data? 

Moved discussion to https://github.com/SpoonLabs/nopol/issues/39.
